### ISSUE TITLE
[BUG] Why can I make Gymnasium environments when using Safety-Gymnasium?

### ISSUE THREAD

**Issue by muchvo** [PKU-MARL/omnisafe#75]
### Required prerequisites

- [X] I have read the documentation <https://omnisafe.readthedocs.io>.
- [X] I have searched the [Issue Tracker](https://github.com/PKU-MARL/omnisafe/issues) and [Discussions](https://github.com/PKU-MARL/omnisafe/discussions) that this hasn't already been reported. (+1 or comment there if it has.)
- [X] Consider asking first in a [Discussion](https://github.com/PKU-MARL/omnisafe/discussions/new).

### What version of OmniSafe are you using?

0.01

### System information

3.8.15 (default, Nov 24 2022, 15:19:38) 
[GCC 11.2.0] linux
0.0.1

### Problem description

When I test safety-gymnasium, I wrongly input 'Humanoid-v4' as env_id, but it works and something goes run.

### Reproducible example code

The Python snippets:

```python
import argparse

import safety_gymnasium


def run_random(env_name):
    """Random run."""
    env = safety_gymnasium.make(env_name, render_mode='human')
    obs, _ = env.reset()
    # Use below to specify seed.
    # obs, _ = env.reset(seed=0)
    terminated, truncated = False, False
    ep_ret, ep_cost = 0, 0
    while True:
        if terminated or truncated:
            print(f'Episode Return: {ep_ret} \t Episode Cost: {ep_cost}')
            ep_ret, ep_cost = 0, 0
            obs, _ = env.reset()
        assert env.observation_space.contains(obs)
        act = env.action_space.sample()
        assert env.action_space.contains(act)
        # Use the environment's built_in max_episode_steps
        if hasattr(env, '_max_episode_steps'):  # pylint: disable=unused-variable
            max_ep_len = env._max_episode_steps  # pylint: disable=unused-variable,protected-access
        # pylint: disable-next=unused-variable
        obs, reward, cost, terminated, truncated, info = env.step(act)

        ep_ret += reward
        ep_cost += cost


if __name__ == '__main__':

    parser = argparse.ArgumentParser()
    parser.add_argument('--env', default='Humanoid-v4')
    args = parser.parse_args()
    run_random(args.env)

```

Command lines:

```bash

```

Extra dependencies:

```text

```

Steps to reproduce:

1. run code above.

### Traceback

```pytb
Traceback (most recent call last):
  File "~/omnisafe/envs/safety_gymnasium/examples/env.py", line 53, in <module>
    run_random(args.env)
  File "~/omnisafe/envs/safety_gymnasium/examples/env.py", line 42, in run_random
    obs, reward, cost, terminated, truncated, info = env.step(act)
  File "~/omnisafe/envs/safety-gymnasium/safety_gymnasium/wrappers/time_limit.py", line 45, in step
    observation, reward, cost, terminated, truncated, info = self.env.step(action)
ValueError: not enough values to unpack (expected 6, got 5)
```

**Comment by zmsn-2077** [comment]
This issue already fixed.
